version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: "Europe/Helsinki"
    open-pull-requests-limit: 5
    groups:
      npm-deps:
        patterns:
          - "*"
    commit-message:
      prefix: "chore"
      include: scope
    labels:
      - dependencies
      - chore

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: "Europe/Helsinki"
    open-pull-requests-limit: 5
    groups:
      github-actions:
        patterns:
          - "*"
    commit-message:
      prefix: "chore"
      include: scope
    labels:
      - dependencies
      - chore
